// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenChecked struct {
	Valid                bool     `protobuf:"varint,1,opt,name=Valid,proto3" json:"Valid,omitempty"`
	Claims               []byte   `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenChecked) Reset()         { *m = TokenChecked{} }
func (m *TokenChecked) String() string { return proto.CompactTextString(m) }
func (*TokenChecked) ProtoMessage()    {}
func (*TokenChecked) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *TokenChecked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenChecked.Unmarshal(m, b)
}
func (m *TokenChecked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenChecked.Marshal(b, m, deterministic)
}
func (m *TokenChecked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenChecked.Merge(m, src)
}
func (m *TokenChecked) XXX_Size() int {
	return xxx_messageInfo_TokenChecked.Size(m)
}
func (m *TokenChecked) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenChecked.DiscardUnknown(m)
}

var xxx_messageInfo_TokenChecked proto.InternalMessageInfo

func (m *TokenChecked) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *TokenChecked) GetClaims() []byte {
	if m != nil {
		return m.Claims
	}
	return nil
}

type TokenPayload struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenPayload) Reset()         { *m = TokenPayload{} }
func (m *TokenPayload) String() string { return proto.CompactTextString(m) }
func (*TokenPayload) ProtoMessage()    {}
func (*TokenPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *TokenPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenPayload.Unmarshal(m, b)
}
func (m *TokenPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenPayload.Marshal(b, m, deterministic)
}
func (m *TokenPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenPayload.Merge(m, src)
}
func (m *TokenPayload) XXX_Size() int {
	return xxx_messageInfo_TokenPayload.Size(m)
}
func (m *TokenPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TokenPayload proto.InternalMessageInfo

func (m *TokenPayload) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenChecked)(nil), "auth_proto.TokenChecked")
	proto.RegisterType((*TokenPayload)(nil), "auth_proto.TokenPayload")
	proto.RegisterType((*Token)(nil), "auth_proto.Token")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x02, 0xb3, 0xe3, 0xc1, 0x6c, 0x25, 0x1b, 0x2e, 0x9e,
	0x90, 0xfc, 0xec, 0xd4, 0x3c, 0xe7, 0x8c, 0xd4, 0xe4, 0xec, 0xd4, 0x14, 0x21, 0x11, 0x2e, 0xd6,
	0xb0, 0xc4, 0x9c, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x08, 0x47, 0x48, 0x8c,
	0x8b, 0x2d, 0x39, 0x27, 0x31, 0x33, 0xb7, 0x58, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xca,
	0x53, 0x92, 0x83, 0xea, 0x0e, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x11, 0xe2, 0xe3, 0x62, 0xf2,
	0x74, 0x01, 0x6b, 0x65, 0x0e, 0x62, 0xf2, 0x74, 0x51, 0x92, 0xe5, 0x62, 0x05, 0xcb, 0x83, 0x8c,
	0x05, 0x33, 0xc0, 0x72, 0x9c, 0x41, 0x10, 0x8e, 0x51, 0x03, 0x23, 0x17, 0xb7, 0x63, 0x69, 0x49,
	0x06, 0xc4, 0xf2, 0x22, 0x21, 0x33, 0x2e, 0x56, 0x30, 0x53, 0x48, 0x50, 0x0f, 0xe1, 0x44, 0x3d,
	0xb0, 0x5a, 0x29, 0x09, 0x0c, 0x21, 0xa8, 0x93, 0x95, 0x18, 0x84, 0x2c, 0xb9, 0x38, 0xdc, 0x53,
	0xf3, 0x52, 0x8b, 0x12, 0x4b, 0x52, 0x85, 0x30, 0xd5, 0x41, 0x1d, 0x27, 0x85, 0x69, 0xa8, 0x12,
	0x43, 0x12, 0x1b, 0x98, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x80, 0x96, 0x58, 0x74, 0x20,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthCheckerClient is the client API for AuthChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthCheckerClient interface {
	Check(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenChecked, error)
	Generate(ctx context.Context, in *TokenPayload, opts ...grpc.CallOption) (*Token, error)
}

type authCheckerClient struct {
	cc *grpc.ClientConn
}

func NewAuthCheckerClient(cc *grpc.ClientConn) AuthCheckerClient {
	return &authCheckerClient{cc}
}

func (c *authCheckerClient) Check(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenChecked, error) {
	out := new(TokenChecked)
	err := c.cc.Invoke(ctx, "/auth_proto.AuthChecker/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authCheckerClient) Generate(ctx context.Context, in *TokenPayload, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/auth_proto.AuthChecker/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthCheckerServer is the server API for AuthChecker service.
type AuthCheckerServer interface {
	Check(context.Context, *Token) (*TokenChecked, error)
	Generate(context.Context, *TokenPayload) (*Token, error)
}

func RegisterAuthCheckerServer(s *grpc.Server, srv AuthCheckerServer) {
	s.RegisterService(&_AuthChecker_serviceDesc, srv)
}

func _AuthChecker_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCheckerServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_proto.AuthChecker/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCheckerServer).Check(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthChecker_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCheckerServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_proto.AuthChecker/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCheckerServer).Generate(ctx, req.(*TokenPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthChecker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth_proto.AuthChecker",
	HandlerType: (*AuthCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _AuthChecker_Check_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _AuthChecker_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
